path: /home/shubham.pandey/opencv/train-yolov8-custom-dataset-step-by-step-guide/Dataset  # dataset root dir
train: train/Person  # train images (relative to 'path')
val: train/Person # val images (relative to 'path')
test: train/Person

# Classes
names:
  0: Person
